apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-name
  namespace: default
  labels:
    app: app-name
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: microk8s-hostpath