apiVersion: v1
kind: Service
metadata:
  name: app-name
  namespace: default
  labels:
    app: app-name
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app-name