security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
    - "method java.lang.Class getCanonicalName"
    - "method org.yaml.snakeyaml.Yaml dump java.lang.Object"
    - "new java.util.HashMap"
    - "new java.util.LinkedHashMap"
    - "new org.yaml.snakeyaml.Yaml"
    - "staticMethod org.apache.commons.codec.digest.DigestUtils md5Hex java.lang.String"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods invokeMethod\
      \ java.lang.Object java.lang.String java.lang.Object"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods println java.lang.Object\
      \ java.lang.Object"
    - "staticMethod org.codehaus.groovy.transform.ImmutableASTTransformation checkPropNames\
      \ java.lang.Object java.util.Map"